import { CriteriaScores, FitRating, PlainLanguageSummary } from './recommendation.types';

/**
 * Presentation-only bucketing for translating a 0-1 score into a traffic-light
 * rating for non-technical readers. Unlike the engine's own thresholds (see
 * thresholds.yaml), these bands don't change which platform wins anything -
 * they only decide how an already-computed score is described in English.
 */
const GREAT_AT_OR_ABOVE = 0.8;
const OK_AT_OR_ABOVE = 0.5;

function rate(score: number): FitRating {
  if (score >= GREAT_AT_OR_ABOVE) return 'great';
  if (score >= OK_AT_OR_ABOVE) return 'ok';
  return 'weak';
}

const CRITERIA_META: Record<
  keyof CriteriaScores,
  { label: string; phrase: string; explanation: Record<FitRating, string> }
> = {
  vectorCount: {
    label: 'Data Volume Capacity',
    phrase: 'data volume capacity',
    explanation: {
      great: 'Comfortably accommodates the projected vector volume.',
      ok: 'Adequate for the current volume; should be monitored as data scales.',
      weak: 'Not well suited to the projected data volume.',
    },
  },
  qps: {
    label: 'Query Throughput',
    phrase: 'query throughput',
    explanation: {
      great: 'Comfortably supports the anticipated query volume.',
      ok: 'Supports the anticipated query volume, though with limited headroom.',
      weak: 'May not sustain the anticipated query volume.',
    },
  },
  latency: {
    label: 'Latency Performance',
    phrase: 'latency performance',
    explanation: {
      great: 'Readily meets the specified response-time target.',
      ok: 'Can likely meet the response-time target, subject to tuning.',
      weak: 'Meeting the specified response-time target will be challenging.',
    },
  },
  recall: {
    label: 'Search Accuracy',
    phrase: 'search accuracy',
    explanation: {
      great: 'Meets the specified search-accuracy requirement.',
      ok: 'Delivers solid, though not best-in-class, search accuracy.',
      weak: 'May fall short of the specified search-accuracy requirement.',
    },
  },
  existingPlatform: {
    label: 'Infrastructure Alignment',
    phrase: 'infrastructure alignment',
    explanation: {
      great: 'Aligns directly with infrastructure already in use, simplifying adoption.',
      ok: 'Shows partial alignment with infrastructure already in use.',
      weak: 'Represents a new platform to operate, with no overlap with current infrastructure.',
    },
  },
  operationalComplexity: {
    label: 'Operational Complexity',
    phrase: 'operational simplicity',
    explanation: {
      great: 'Requires minimal ongoing operational effort.',
      ok: 'Requires a moderate level of ongoing operational effort.',
      weak: 'Requires significant ongoing operational effort.',
    },
  },
  cost: {
    label: 'Cost Efficiency',
    phrase: 'cost efficiency',
    explanation: {
      great: 'Represents one of the more cost-effective options evaluated.',
      ok: 'Represents a reasonably cost-effective option.',
      weak: 'Likely to be more costly than the alternatives evaluated.',
    },
  },
};

const CRITERIA_ORDER: (keyof CriteriaScores)[] = [
  'vectorCount',
  'qps',
  'latency',
  'recall',
  'existingPlatform',
  'operationalComplexity',
  'cost',
];

/** Known exact risk strings produced by RecommendationEngineService.buildRisks(), reworded for an executive audience. */
const RISK_REWRITES: Array<{ prefix: string; plain: string }> = [
  {
    prefix: 'No existing Kubernetes platform was reported',
    plain: 'Kubernetes infrastructure is not currently in place; a new cluster will need to be provisioned before this platform can be deployed.',
  },
  {
    prefix: 'High recall target may require larger ef/nprobe search parameters',
    plain: 'The specified recall target may require larger search parameters during index tuning, which could modestly increase latency or memory utilization.',
  },
  {
    prefix: 'Strict P95 latency target is aggressive',
    plain: 'The specified latency target is ambitious at this scale; load-testing under realistic conditions is recommended before committing to this service-level target.',
  },
  {
    prefix: 'Workload contains PII',
    plain: 'As the dataset contains personally identifiable information, encryption and data-residency controls should be verified end-to-end.',
  },
  {
    prefix: 'No material risks identified',
    plain: 'No material risks were identified based on the information provided. Standard operational considerations, such as capacity monitoring, continue to apply.',
  },
  {
    prefix: 'No maintained Node.js driver exists',
    plain:
      'This platform has no maintained Node.js driver, so while its schema, index design, deployment plan, and capacity ' +
      'forecast are fully generated by this tool, actually loading data into it requires a database-specific bridge set up ' +
      'outside this tool.',
  },
];

function simplifyRisk(risk: string): string {
  return RISK_REWRITES.find((r) => risk.startsWith(r.prefix))?.plain ?? risk;
}

function verdictFor(totalScore: number): PlainLanguageSummary['verdict'] {
  if (totalScore >= 0.85) return 'Excellent Fit';
  if (totalScore >= 0.7) return 'Good Fit';
  if (totalScore >= 0.55) return 'Workable Fit';
  return 'Weak Fit';
}

export function buildPlainLanguageSummary(
  winnerLabel: string,
  totalScore: number,
  criteriaScores: CriteriaScores,
  risks: string[],
): PlainLanguageSummary {
  const scorecard = CRITERIA_ORDER.map((key) => {
    const rating = rate(criteriaScores[key]);
    return { label: CRITERIA_META[key].label, rating, explanation: CRITERIA_META[key].explanation[rating] };
  });

  const byScore = CRITERIA_ORDER.map((key) => ({ key, score: criteriaScores[key] })).sort((a, b) => b.score - a.score);
  const weakest = byScore[byScore.length - 1];
  const strongest = byScore.slice(0, 2).map((c) => CRITERIA_META[c.key].phrase);

  const headline =
    weakest.score >= GREAT_AT_OR_ABOVE
      ? `${winnerLabel} performs strongly across every criterion evaluated for this project.`
      : `${winnerLabel} is the recommended platform, reflecting strong alignment with ${strongest.join(' and ')}. The primary limitation is ${CRITERIA_META[weakest.key].phrase}.`;

  const costAndEffort = `${CRITERIA_META.operationalComplexity.explanation[rate(criteriaScores.operationalComplexity)]} ${CRITERIA_META.cost.explanation[rate(criteriaScores.cost)]}`;

  const verdict = verdictFor(totalScore);
  const bottomLine =
    verdict === 'Weak Fit'
      ? `${winnerLabel} is the strongest of the options evaluated, but does not represent a strong overall fit. We recommend revisiting the project requirements or considering a manual platform override.`
      : `${winnerLabel} represents a sound platform choice for this project. We recommend reviewing the considerations noted above before proceeding to Phase 2 (Data Pipeline Design).`;

  return {
    verdict,
    headline,
    scorecard,
    costAndEffort,
    risks: risks.map(simplifyRisk),
    bottomLine,
  };
}
